language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev" # 3.7 development branch
# install requirements
install: "pip install pytest-pep8 pytest-cov coveralls python-coveralls"
# command to run tests
script: "py.test --pep8 --cov alphabet_detector --cov-report term-missing"
after_success: coveralls